#!/usr/bin/python -u
# -*- coding: utf-8 -*-

# TFN 180417 added two different modes to generate html file for mail service or web server usage
# TFN 130317 extented output by adding yearly summaries
# TFN 130317 directly generating min-max-values.html because including WeSta_statistic_data.html only worked with Firefox
# TFN 120317 generating html file to show statistic data in table format
# TFN 260217 switch to new table format
# TFN 190117 align values in table; hate Umlaute...
# TFN 190117 dump static data out of MySQL database

from __future__ import print_function

import sys
import datetime
import MySQLdb
from time import *


def main():
  #fileName = "min-max-values_generated.html"
  fileName = sys.argv[1]
  MailMode = sys.argv[2]

  DEBUG = False
  TEST  = False
  
  monthArray = ['Januar','Februar','März','April','Mai','Juni','Juli', 'August','September','Oktober','November','Dezember']
  curYear    = int(strftime("%Y", localtime()))
  curMonth   = int(strftime("%m", localtime()))
  startYear  = 2017 # first year of weather recordings
 
  try:
    fh = open(fileName,"w")

    db = MySQLdb.connect("localhost", "pi","","temps")
    curs = db.cursor()
    
    print ("<!doctype html>", file=fh)
    print ("<html>", file=fh)

    print ("<!-- *** this file was generated by dumpStatistics.py *** -->", file=fh)
    
    print ("<head>", file=fh)
    print ("  <style>", file=fh)
    print ("    body {", file=fh)
    print ("      background-color: #e0e0e0;", file=fh)
    print ("      font-family: Arial;", file=fh)
    print ("    }", file=fh)
    print ("    table, th, td {", file=fh)
    print ("      border: 1px solid black;", file=fh)
    print ("      border-collapse: collapse;", file=fh)
    #    print ("      width: 70%;", file=fh) automatic width definition is more readable
    print ("      height: 30px;", file=fh)
    print ("    }", file=fh)
    print ("    #tabelle        {background-color: antiquewhite}", file=fh)
    print ("    #zeilengruppe   {background-color: navajowhite; color: black}", file=fh)
    print ("    .kursiv         {font-style: italic;}", file=fh)
    print ("    th, td          {padding: 2px;}", file=fh)
    print ("    th              {text-align: center;}", file=fh)
    print ("    td              {text-align: center;}", file=fh)
    print ("  </style>", file=fh)
    print ("  <meta charset=\"utf-8\">", file=fh)
    print ("</head>", file=fh)

    print ("<body>", file=fh)

    if MailMode == False:
      print ("  <h1>Historiendaten: Statistische Werte</h1>", file=fh)
      print ("  <ul>", file=fh)
      print ("    <li><a href=\"../index.php\">zurück zur Hauptseite</a></li>", file=fh)
      print ("  </ul>", file=fh)
    
    print ("  <h6 class=\"kursiv\">Tabellen generiert um: ", strftime("%d-%m-%Y %H:%M:%S", localtime()), file=fh)
    print ("  </h6>", file=fh)

    print ("<table id=\"tabelle\">", file=fh)
    print ("  <caption>", file=fh)
    print ("    Daten der letzten 12 Monate", file=fh)
    print ("  </caption>", file=fh)

    #
    # generate table with last 12 month 
    #

    print ("  <tbody id=\"zeilengruppe\">", file=fh)

    # iterate over *head* row elements to generate first row
    print ("    <tr>", file=fh)
    s = 0
    while s <= 12:
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <th>", file=fh)
        print ("      </th>", file=fh)        
      else:
        if DEBUG:
          print ("Monat: ", monthArray[curMonth-1])

        print ("      <th>", file=fh)
        print ("        ",monthArray[curMonth-1], file=fh)
        print ("      </th>", file=fh)
        
        curMonth -= 1
        if curMonth == 0:
          curMonth = 12
      s += 1
    print ("    </tr>", file=fh)
    print ("  </tbody>", file=fh)

    # iterate over *secound* row elements
    print ("  <tr>", file=fh)
    curMonth = int(strftime("%m", localtime()))
    s = 0
    while s <= 12:
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("    <td>", file=fh)
        print ("      Regentage", file=fh)
        print ("    </td>", file=fh)        
      else:
        if DEBUG:
          print ("Monat: ", monthArray[curMonth-1])

        print ("    <td>", file=fh)       
        curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Type = 'Regentage'",(monthArray[curMonth-1],))
        for reading in curs.fetchall():
          print ("      ",int(reading[4]), file=fh)
        print ("    </td>", file=fh)
        
        curMonth -= 1
        if curMonth == 0:
          curMonth = 12
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *third* row elements
    print ("  <tr>", file=fh)
    curMonth = int(strftime("%m", localtime()))
    s = 0
    while s <= 12:
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("    <td>", file=fh)
        print ("      Frosttage", file=fh)
        print ("    </td>", file=fh)        
      else:
        if DEBUG:
          print ("Monat: ", monthArray[curMonth-1])

        print ("    <td>", file=fh)       
        curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Type = 'Frosttage'",(monthArray[curMonth-1],))
        for reading in curs.fetchall():
          print ("      ",int(reading[4]), file=fh)
        print ("    </td>", file=fh)
        
        curMonth -= 1
        if curMonth == 0:
          curMonth = 12
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *forth* row elements
    print ("  <tr>", file=fh)
    curMonth = int(strftime("%m", localtime()))
    s = 0
    while s <= 12:
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("    <td>", file=fh)
        print ("      Dauerfrosttage", file=fh)
        print ("    </td>", file=fh)        
      else:
        if DEBUG:
          print ("Monat: ", monthArray[curMonth-1])

        print ("    <td>", file=fh)       
        curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Type = 'Dauerfrosttage'",(monthArray[curMonth-1],))
        for reading in curs.fetchall():
          print ("      ",int(reading[4]), file=fh)
        print ("    </td>", file=fh)
        
        curMonth -= 1
        if curMonth == 0:
          curMonth = 12
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *fifth* row elements
    print ("  <tr>", file=fh)
    curMonth = int(strftime("%m", localtime()))
    s = 0
    while s <= 12:
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("    <td>", file=fh)
        print ("      Tropische Nächte (>20°C)", file=fh)
        print ("    </td>", file=fh)        
      else:
        if DEBUG:
          print ("Monat: ", monthArray[curMonth-1])

        print ("    <td>", file=fh)       
        curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Type = 'Tropische Nächte'",(monthArray[curMonth-1],))
        for reading in curs.fetchall():
          print ("      ",int(reading[4]), file=fh)
        print ("    </td>", file=fh)
        
        curMonth -= 1
        if curMonth == 0:
          curMonth = 12
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *sixth* row elements
    print ("  <tr>", file=fh)
    curMonth = int(strftime("%m", localtime()))
    s = 0
    while s <= 12:
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("    <td>", file=fh)
        print ("      min. Außentemperatur in °C", file=fh)
        print ("    </td>", file=fh)        
      else:
        if DEBUG:
          print ("Monat: ", monthArray[curMonth-1])

        print ("    <td>", file=fh)       
        curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Außentemperatur' AND Type = 'min'", \
          (monthArray[curMonth-1],))
        for reading in curs.fetchall():
          print ("      ",reading[4], file=fh)
        print ("    </td>", file=fh)
        
        curMonth -= 1
        if curMonth == 0:
          curMonth = 12
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *seventh* row elements
    print ("  <tr>", file=fh)
    curMonth = int(strftime("%m", localtime()))
    s = 0
    while s <= 12:
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("    <td>", file=fh)
        print ("      max. Außentemperatur in °C", file=fh)
        print ("    </td>", file=fh)        
      else:
        if DEBUG:
          print ("Monat: ", monthArray[curMonth-1])

        print ("    <td>", file=fh)       
        curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Außentemperatur' AND Type = 'max'", \
          (monthArray[curMonth-1],))
        for reading in curs.fetchall():
          print ("      ",reading[4], file=fh)
        print ("    </td>", file=fh)
        
        curMonth -= 1
        if curMonth == 0:
          curMonth = 12
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *eighth* row elements
    print ("  <tr>", file=fh)
    curMonth = int(strftime("%m", localtime()))
    s = 0
    while s <= 12:
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("    <td>", file=fh)
        print ("      max. Tagestemperaturdelta in °C", file=fh)
        print ("    </td>", file=fh)        
      else:
        if DEBUG:
          print ("Monat: ", monthArray[curMonth-1])

        print ("    <td>", file=fh)       
        curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Außentemperatur' AND Type = 'MaxDelta'", \
          (monthArray[curMonth-1],))
        for reading in curs.fetchall():
          print ("      ",reading[4], file=fh)
        print ("    </td>", file=fh)
        
        curMonth -= 1
        if curMonth == 0:
          curMonth = 12
      s += 1
    print ("  </tr>", file=fh)
    print ("</table>", file=fh)

    #
    # generate table for yearly summaries
    #
    if TEST:
        curYear = 2020

    print ("<h1></h1>", file=fh)

    print ("<table id=\"tabelle\">", file=fh)
    print ("  <caption>", file=fh)
    print ("    Jahresübersichten", file=fh)
    print ("  </caption>", file=fh)

    print ("  <tbody id=\"zeilengruppe\">", file=fh)
    # iterate over *head* row elements to generate first row with years
    print ("    <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column (empty)
        print ("      <th>", file=fh)
        print ("      </th>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <th>", file=fh)
          print ("        all time", file=fh)
          print ("      </th>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <th>", file=fh)
          print ("        ", Year, file=fh)
          print ("      </th>", file=fh)          
          Year -= 1    
      s += 1
    print ("    </tr>", file=fh)
    print ("  </tbody>", file=fh)

    # iterate over *secound* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      Regentage", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          print ("      -", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Regenfall' AND Type = 'Regentage'", \
                       (Year,))
          for reading in curs.fetchall():
            print ("      ",int(reading[4]), file=fh)
          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *third* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      Frosttage", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          print ("      -", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Außentemperatur' AND Type = 'Frosttage'", \
                       (Year,))
          for reading in curs.fetchall():
            print ("      ",int(reading[4]), file=fh)
          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *third* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      Dauerfrosttage", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          print ("      -", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Außentemperatur' AND Type = 'Dauerfrosttage'", \
                       (Year,))
          for reading in curs.fetchall():
            print ("      ",int(reading[4]), file=fh)
          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *forth* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      Tropische Nächte (>20°C)", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          print ("      -", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Außentemperatur' AND Type = 'Tropische Nächte'", \
                       (Year,))
          for reading in curs.fetchall():
            print ("      ",int(reading[4]), file=fh)
          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *fith* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      min. Außentemperatur in °C", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = 'all time' AND Sensor = 'Außentemperatur' AND Type = 'min'")
          for reading in curs.fetchall():
            print ("      ",reading[4], "<br /><font size=\"-2\">(",reading[7], ")</font>", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Außentemperatur' AND Type = 'min'", \
                       (Year,))
          for reading in curs.fetchall():
            print ("      ",reading[4], "<br /><font size=\"-2\">(",reading[7], ")</font>", file=fh)

          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)


    # iterate over *sixth* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      max. Außentemperatur in °C", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = 'all time' AND Sensor = 'Außentemperatur' AND Type = 'max'")
          for reading in curs.fetchall():
            print ("      ",reading[4], "<br /><font size=\"-2\">(",reading[7], ")</font>", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Außentemperatur' AND Type = 'max'", \
                       (Year,))
          for reading in curs.fetchall():
            print ("      ",reading[4], "<br /><font size=\"-2\">(",reading[7], ")</font>", file=fh)

          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *seventh* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      max. Tagestemperaturdelta in °C", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = 'all time' AND Sensor = 'Außentemperatur' AND Type = 'MaxDelta'")
          for reading in curs.fetchall():
            print ("      ",reading[4], "<br /><font size=\"-2\">(",reading[7], ")</font>", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = %s AND Sensor = 'Außentemperatur' AND Type = 'MaxDelta'", \
                       (Year,))
          for reading in curs.fetchall():
            print ("      ",reading[4], "<br /><font size=\"-2\">(",reading[7], ")</font>", file=fh)

          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *eighths* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      max. Windgeschwindigkeit in km/h", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = 'all time' AND Sensor = 'Windgeschwindigkeit' AND Type = 'max'")
          for reading in curs.fetchall():
            print ("      ",reading[4], "<br /><font size=\"-2\">(",reading[7], ")</font>", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          print ("      -", file=fh)
          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *ninth* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      max. Luftdruck in hPa", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = 'all time' AND Sensor = 'Luftdruck' AND Type = 'max'")
          for reading in curs.fetchall():
            print ("      ",reading[4], "<br /><font size=\"-2\">(",reading[7], ")</font>", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          print ("      -", file=fh)
          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)

    # iterate over *tenth* row elements
    print ("  <tr>", file=fh)
    s = 0
    Year = curYear
    while s <= (curYear+2-startYear):
      if DEBUG:
        print ("Spalte: ", s) 
      if s == 0:
        # first column
        print ("      <td>", file=fh)
        print ("      min. Luftdruck in hPa", file=fh)
        print ("      </td>", file=fh)        
      else:
        if s == 1:
          # secound column (all time)        
          if DEBUG:
            print ("Jahr: all time")
          print ("      <td>", file=fh)
          curs.execute("SELECT * FROM tbl_WeSta_values2 WHERE Periode = 'all time' AND Sensor = 'Luftdruck' AND Type = 'min'")
          for reading in curs.fetchall():
            print ("      ",reading[4], "<br /><font size=\"-2\">(",reading[7], ")</font>", file=fh)
          print ("      </td>", file=fh)          
        else:
          if DEBUG:
            print ("Jahr: ", Year)
          print ("      <td>", file=fh)
          print ("      -", file=fh)
          print ("      </td>", file=fh)          
          Year -= 1    
      s += 1
    print ("  </tr>", file=fh)

    print ("</body>", file=fh)
    print ("</html>", file=fh)

    fh.close()   
    db.close()
    
  except MySQLdb.Error, e:
    try:
        print ("MySQL Error [%d]: %s" % (e.args[0], e.args[1]))
    except IndexError:
        print ("MySQL Error: %s" % str(e))
            
    print ("Error: will rollback database")
    db.rollback()
    db.close()

if __name__ == '__main__':
  main()
